"""
Component behaviour: availability providers, the ANSI parser, history merging.

The console parser gets the most attention here because two of its cases are
invisible until they are wrong in front of a user: a pty turns every '\n' into
'\r\n', and capture.sh redraws its progress bar with a bare '\r'. Confusing the
two either erases completed output or stacks a hundred progress-bar lines.
"""

import os
import tempfile
import time
import unittest

from sreto import ansi_console, history, jobs, paths, prechecks
from sreto import soop_availability as sa

from .support import requires_science_repo

PLAN_HEADER = "\t".join(sa.PLAN_COLUMNS)


def _plan_row(name, catnr, rise, dur, elev, freq=1621.25, sr=10.0, geo="0"):
    return "\t".join([
        str(rise), str(rise + dur), str(rise + dur / 2), str(dur), str(elev),
        str(freq), str(sr), str(sr), geo, str(catnr), name,
        "2026-01-01 00:00:00Z", "2026-01-01 00:10:00Z", "1 x", "2 x",
    ])


class TestAvailabilityProviders(unittest.TestCase):

    def test_placeholder_is_flagged_everywhere(self):
        provider = sa.get_provider("placeholder")
        self.assertTrue(provider.is_placeholder)
        passes = provider.passes(horizon_h=24, min_elev_deg=0)
        self.assertTrue(passes, "the placeholder produced nothing to show")
        for p in passes:
            self.assertIn("PLACEHOLDER", p.name)
            self.assertEqual(p.source, "placeholder")

    def test_placeholder_is_stable_between_refreshes(self):
        provider = sa.get_provider("placeholder")
        first = [(p.name, round(p.rise_unix)) for p in provider.passes()]
        second = [(p.name, round(p.rise_unix)) for p in provider.passes()]
        self.assertEqual(first, second,
                         "the placeholder jitters between refreshes, which "
                         "would make the table unreadable")

    def test_plan_provider_parses_a_written_plan(self):
        now = time.time()
        with tempfile.TemporaryDirectory() as tmp:
            plan = os.path.join(tmp, "plan.tsv")
            with open(plan, "w") as f:
                f.write("# generated by a test\n")
                f.write(f"# columns: {PLAN_HEADER}\n")
                f.write(_plan_row("IRIDIUM 113", 42803, now + 600, 540, 83.1) + "\n")
                f.write(_plan_row("GLOBALSTAR M07", 39075, now + 3600, 300, 22.0) + "\n")
                f.write(_plan_row("LOW PASS", 1, now + 300, 120, 3.0) + "\n")

            provider = sa.CapturePlanProvider(plan)
            self.assertTrue(provider.available()[0])

            passes = provider.passes(horizon_h=24, min_elev_deg=10)
            self.assertEqual([p.name for p in passes],
                             ["IRIDIUM 113", "GLOBALSTAR M07"],
                             "the elevation mask was not applied")
            self.assertEqual(passes[0].catnr, "42803")
            self.assertAlmostEqual(passes[0].peak_el_deg, 83.1)
            self.assertAlmostEqual(passes[0].duration_s, 540.0)

    def test_plan_provider_reports_a_missing_plan_instead_of_raising(self):
        provider = sa.CapturePlanProvider("/nonexistent/plan.tsv")
        ok, reason = provider.available()
        self.assertFalse(ok)
        self.assertIn("plan", reason.lower())
        self.assertEqual(provider.passes(), [])

    def test_horizon_filter(self):
        now = time.time()
        with tempfile.TemporaryDirectory() as tmp:
            plan = os.path.join(tmp, "plan.tsv")
            with open(plan, "w") as f:
                f.write(_plan_row("SOON", 1, now + 1800, 300, 40) + "\n")
                f.write(_plan_row("LATER", 2, now + 40 * 3600, 300, 40) + "\n")
            provider = sa.CapturePlanProvider(plan)
            self.assertEqual([p.name for p in provider.passes(horizon_h=24)],
                             ["SOON"])
            self.assertEqual(len(provider.passes(horizon_h=48)), 2)

    def test_pass_state_and_gb_estimate(self):
        now = time.time()
        p = sa.SatellitePass(name="X", rise_unix=now - 10, set_unix=now + 10,
                             samplerate_mhz=10.0)
        self.assertEqual(p.state(now), "now")
        self.assertEqual(sa.SatellitePass(name="X", rise_unix=now + 60,
                                          set_unix=now + 120).state(now), "upcoming")
        self.assertEqual(sa.SatellitePass(name="X", rise_unix=now - 120,
                                          set_unix=now - 60).state(now), "past")
        # 20 s at 10 MS/s, 2 ch, 16 bit = 20 * 10e6 * 8 bytes = 1.6 GB
        self.assertAlmostEqual(p.estimated_gb(), 1.6, places=2)

    def test_geo_targets_read_as_permanently_up(self):
        now = time.time()
        p = sa.SatellitePass(name="GEO", rise_unix=now - 1e6, set_unix=now - 1e5,
                             geo=True)
        self.assertEqual(p.state(now), "now")

    def test_custom_provider_can_be_registered(self):
        class Fake(sa.Provider):
            name = "unit-test-provider"
            label = "Unit test provider"

            def passes(self, horizon_h=24.0, min_elev_deg=10.0):
                return [sa.SatellitePass(name="FAKE", rise_unix=time.time())]

        sa.register_provider(Fake())
        self.addCleanup(sa._PROVIDERS.pop, "unit-test-provider", None)
        self.assertIn("Unit test provider", [p.label for p in sa.providers()])
        self.assertEqual(sa.get_provider("unit-test-provider").passes()[0].name,
                         "FAKE")

    def test_countdown_formatting(self):
        self.assertEqual(sa.fmt_countdown(0), "now")
        self.assertTrue(sa.fmt_countdown(45).startswith("in 45s"))
        self.assertIn("ago", sa.fmt_countdown(-120))
        self.assertIn("h", sa.fmt_countdown(7200))
        self.assertIn("d", sa.fmt_countdown(200000))


class TestAnsiParsing(unittest.TestCase):
    """Parser logic only — no Tk widget is created."""

    def test_strip_ansi_removes_colour_and_carriage_returns(self):
        raw = "\033[32mYAYYYY\033[0m\r\nnext\r"
        self.assertEqual(ansi_console.strip_ansi(raw), "YAYYYY\nnext")

    def test_sgr_regex_matches_console_py_codes(self):
        for code in ("\033[1m", "\033[2m", "\033[32m", "\033[33m", "\033[31m",
                     "\033[36m", "\033[35m", "\033[0m"):
            self.assertIsNotNone(ansi_console._CSI_RE.match(code), code)

    def test_partial_escape_is_detected_for_buffering(self):
        for tail in ("\033", "\033[", "\033[3", "\033[38;5;"):
            self.assertIsNotNone(ansi_console._PARTIAL_ESC_RE.search("text" + tail),
                                 f"{tail!r} would be printed as garbage")
        self.assertIsNone(ansi_console._PARTIAL_ESC_RE.search("plain text"))

    def test_complete_escape_is_never_held_back(self):
        """A finished sequence must render now, not wait for the next read."""
        for text in ("a\033[32m", "\033[0m", "line\033[36mcyan\033[0m"):
            self.assertIsNone(
                ansi_console._PARTIAL_ESC_RE.search(text),
                f"{text!r} ends in a COMPLETE sequence but would be buffered, "
                f"delaying output until more bytes arrive")


class TestThreadSafety(unittest.TestCase):
    """The runner's reader thread must never touch Tk.

    `root.after()` from a worker thread happens to work while mainloop() is
    spinning and raises 'main thread is not in main loop' when it is not — and
    the raise lands in the reader thread, killing the completion handler
    silently: the job never finishes, Stop stays armed, and the journal keeps a
    RUNNING row forever. Checked statically so the suite stays headless.
    """

    TK_MARKERS = ("self.root.", "self.console.", "self.stop_btn",
                  "self.job_chip", "self.status_label", ".configure(",
                  ".after(", "messagebox")

    def _source_of(self, name):
        """Executable body of App.<name>, docstring excluded.

        The docstring is stripped because these methods DESCRIBE the pattern
        they avoid — scanning the prose would flag the explanation itself.
        """
        import ast
        import inspect

        from sreto import app as app_module
        tree = ast.parse(inspect.getsource(app_module.App))
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == name:
                body = node.body
                if (body and isinstance(body[0], ast.Expr)
                        and isinstance(body[0].value, ast.Constant)
                        and isinstance(body[0].value.value, str)):
                    body = body[1:]
                return "\n".join(ast.unparse(n) for n in body)
        self.fail(f"App.{name} not found")

    def test_on_job_exit_touches_no_tk(self):
        src = self._source_of("_on_job_exit")
        offenders = [m for m in self.TK_MARKERS if m in src]
        self.assertEqual(
            offenders, [],
            f"App._on_job_exit runs on the reader thread but references "
            f"{offenders} — hand the handle to a queue instead and let the "
            f"main thread drain it.")

    def test_the_handover_queue_exists_and_is_drained_on_a_timer(self):
        src = self._source_of("_poll_exits")
        self.assertIn("_exit_queue", src)
        self.assertIn("after", src, "_poll_exits must reschedule itself")

    def test_precheck_worker_also_stays_off_the_tk_thread(self):
        import ast
        import inspect

        from sreto.panels import precheck_panel
        tree = ast.parse(inspect.getsource(precheck_panel.PrecheckPanel))
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "_worker":
                src = ast.unparse(node)
                self.assertNotIn("self.tree", src)
                self.assertNotIn("configure", src)
                return
        self.fail("PrecheckPanel._worker not found")


class TestCaptureEstimate(unittest.TestCase):

    def test_matches_capture_sh_arithmetic(self):
        # 120 s at 10 MS/s, 2 channels, 16-bit = 120*10e6*2*4 bytes = 9.6 GB
        size, duration, readable = jobs.estimate_capture(
            {"samplerate": "10", "channels": "1,2", "bitmode": "16bit",
             "capture_mode": "2", "amount": "120"})
        self.assertEqual(size, 9.6e9)
        self.assertEqual(duration, 120)
        self.assertIn("GB", readable)

    def test_single_channel_halves_it(self):
        size, _d, _r = jobs.estimate_capture(
            {"samplerate": "10", "channels": "1", "capture_mode": "2",
             "amount": "120"})
        self.assertEqual(size, 4.8e9)

    def test_8bit_halves_it(self):
        size, _d, _r = jobs.estimate_capture(
            {"samplerate": "10", "channels": "1,2", "bitmode": "8bit",
             "capture_mode": "2", "amount": "120"})
        self.assertEqual(size, 4.8e9)

    def test_sample_count_mode(self):
        size, duration, _r = jobs.estimate_capture(
            {"samplerate": "2", "channels": "1,2", "capture_mode": "1",
             "amount": "10"})
        self.assertEqual(size, 10e6 * 2 * 4)
        self.assertEqual(duration, 5)

    def test_blank_form_uses_the_scripts_defaults(self):
        size, duration, _r = jobs.estimate_capture({})
        self.assertEqual(duration, 10)          # capture.sh's default timeout
        self.assertEqual(size, 10 * 2e6 * 2 * 4)

    def test_bad_input_is_reported_not_raised(self):
        size, duration, reason = jobs.estimate_capture({"samplerate": "abc"})
        self.assertIsNone(size)
        self.assertIsNone(duration)
        self.assertIn("numeric", reason)

    def test_human_bytes_matches_the_shell_formatter(self):
        self.assertEqual(jobs.human_bytes(1024), "1.00 KB")
        self.assertEqual(jobs.human_bytes(1536), "1.50 KB")
        self.assertEqual(jobs.human_bytes(0), "0.00 B")


class TestHistory(unittest.TestCase):

    def test_master_log_is_readable(self):
        rows = history.read_master_log()
        self.assertIsInstance(rows, list)
        if rows:
            self.assertIn("Filename", rows[0])

    def test_rows_are_newest_first(self):
        rows = history.merged_rows()
        times = [r.unix for r in rows]
        self.assertEqual(times, sorted(times, reverse=True))

    def test_status_is_never_silently_optimistic(self):
        """A row from before Capture_Status existed must not read as SUCCESS."""
        failures = history.read_failures()
        status = history._status_for_capture({"Timestamp": "20200101_000000"},
                                             failures)
        self.assertEqual(status, "UNKNOWN")

    def test_duration_formatting(self):
        self.assertEqual(history.fmt_duration(45), "45s")
        self.assertEqual(history.fmt_duration(125), "2m 05s")
        self.assertEqual(history.fmt_duration(3725), "1h 02m")
        self.assertEqual(history.fmt_duration(None), "")

    def test_berlin_formatting_is_not_utc(self):
        # 2026-07-01 12:00:00 UTC is 14:00 in Berlin (CEST).
        self.assertEqual(history.fmt_berlin(1782043200.0, "%H:%M"), "14:00")

    def test_journal_round_trip(self):
        run_id = f"unittest-{int(time.time() * 1000)}"
        history.append_journal({"run_id": run_id, "event": "start",
                                "kind": "analysis", "summary": "unit test",
                                "started_unix": time.time(), "status": "RUNNING"})
        history.update_journal_entry(run_id, status="SUCCESS", duration_sec=1.5)
        rows = [r for r in history.journal_rows() if r.raw.get("run_id") == run_id]
        self.assertEqual(len(rows), 1, "start and end were not folded together")
        self.assertEqual(rows[0].status, "SUCCESS")


class TestPrechecks(unittest.TestCase):

    def test_run_all_without_the_radio_never_raises(self):
        results = prechecks.run_all(probe_radio=False)
        self.assertTrue(results)
        for c in results:
            self.assertIn(c.status, (prechecks.OK, prechecks.WARN,
                                     prechecks.FAIL, prechecks.INFO))

    def test_failures_carry_a_fix(self):
        for c in prechecks.run_all(probe_radio=False):
            if c.status == prechecks.FAIL:
                self.assertTrue(c.hint or c.detail,
                                f"{c.name} failed with no explanation")

    def test_summarise_reports_the_worst_status(self):
        worst, counts = prechecks.summarise([
            prechecks.Check("a", prechecks.OK, ""),
            prechecks.Check("b", prechecks.WARN, ""),
            prechecks.Check("c", prechecks.FAIL, ""),
        ])
        self.assertEqual(worst, prechecks.FAIL)
        self.assertEqual(counts[prechecks.OK], 1)

    @requires_science_repo
    def test_thresholds_match_the_shell_scripts(self):
        """The one test in this module that reads the science repo's scripts."""
        with open(paths.SOOP_CAPTURE_SH, encoding="utf-8") as f:
            src = f.read()
        self.assertIn(f"DISK_HEADROOM_GB={int(prechecks.DISK_HEADROOM_GB)}", src)
        self.assertIn(f"PLAN_MAX_AGE_H={int(prechecks.PLAN_MAX_AGE_H)}", src)

    def test_a_capture_only_machine_does_not_get_a_red_board(self):
        """The field Pi has no numpy and does not need one.

        These modules belong to the ANALYSIS chain. Failing the board for them
        would tell an operator whose rig is perfectly able to record that it is
        broken, and the lesson learned is to stop reading the board.
        """
        for c in prechecks.check_python_env():
            self.assertNotEqual(
                c.status, prechecks.FAIL,
                f"{c.name} is FAIL, but capture needs no third-party package")


class TestUsbLinkSpeed(unittest.TestCase):
    """A bladeRF that quietly enumerated on USB 2 records SHORT files.

    Nothing else in the board catches it: the device is found, the probe
    succeeds, the capture starts. Built against a fake sysfs so the Linux
    branch — the one that matters, because that is where the field Pi is — is
    actually exercised on the machine this is developed on.
    """

    def _sysfs(self, *devices):
        import shutil
        root = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, root, True)
        for name, vendor, speed in devices:
            d = os.path.join(root, name)
            os.makedirs(d)
            with open(os.path.join(d, "idVendor"), "w") as f:
                f.write(vendor + "\n")
            with open(os.path.join(d, "speed"), "w") as f:
                f.write(speed + "\n")
        return root

    def _one(self, *devices):
        checks = prechecks.check_usb_link(self._sysfs(*devices))
        self.assertEqual(len(checks), 1)
        return checks[0]

    def test_superspeed_passes(self):
        check = self._one(("2-1", "2cf0", "5000"))
        self.assertEqual(check.status, prechecks.OK)

    def test_high_speed_is_a_failure_with_the_fix_in_the_hint(self):
        check = self._one(("1-1", "2cf0", "480"))
        self.assertEqual(check.status, prechecks.FAIL)
        self.assertIn("USB 3", check.hint)

    def test_it_ignores_other_devices_on_the_bus(self):
        """A USB 2 hub next to a SuperSpeed bladeRF must not read as a fault."""
        check = self._one(("1-1", "1d6b", "480"), ("2-1", "2cf0", "5000"))
        self.assertEqual(check.status, prechecks.OK)

    def test_no_radio_is_information_not_a_failure(self):
        check = self._one(("1-1", "1d6b", "480"))
        self.assertEqual(check.status, prechecks.INFO)

    def test_an_unreadable_speed_does_not_crash(self):
        check = self._one(("1-1", "2cf0", "not-a-number"))
        self.assertEqual(check.status, prechecks.WARN)

    def test_a_machine_without_sysfs_says_so_rather_than_failing(self):
        check = prechecks.check_usb_link(os.path.join(tempfile.gettempdir(),
                                                      "definitely-not-sysfs"))
        self.assertEqual(check[0].status, prechecks.INFO)


class TestSustainedWriteRate(unittest.TestCase):
    """The number that decides SUCCESS vs a SHORT file on a slow disk."""

    def test_it_matches_the_figure_the_scripts_quote(self):
        """soop_capture.sh's own header says 10 MS/s 2ch 16bit = 0.8 GB per
        10 s. That is 80 MB/s, and it is the threshold a Pi's microSD fails."""
        rate = jobs.capture_rate_bytes_per_sec(
            {"samplerate": "10", "channels": "1,2", "bitmode": "16bit"})
        self.assertAlmostEqual(rate / 1e6, 80.0)

    def test_single_channel_and_8bit_each_halve_it(self):
        base = {"samplerate": "10", "channels": "1,2", "bitmode": "16bit"}
        full = jobs.capture_rate_bytes_per_sec(base)
        self.assertAlmostEqual(
            jobs.capture_rate_bytes_per_sec(dict(base, channels="1")), full / 2)
        self.assertAlmostEqual(
            jobs.capture_rate_bytes_per_sec(dict(base, bitmode="8bit")), full / 2)

    def test_it_agrees_with_capture_sh_s_own_size_arithmetic(self):
        """rate x duration must equal the size estimate, or one of the two is
        lying to the user about the same capture."""
        values = {"samplerate": "5", "channels": "1,2", "bitmode": "16bit",
                  "capture_mode": "2", "amount": "20"}
        size, duration, _readable = jobs.estimate_capture(values)
        rate = jobs.capture_rate_bytes_per_sec(values)
        self.assertAlmostEqual(rate * duration, size)

    def test_a_blank_form_does_not_crash_it(self):
        self.assertIsNone(jobs.capture_rate_bytes_per_sec({"samplerate": "nope"}))
        self.assertIsNone(jobs.capture_rate_bytes_per_sec({"samplerate": "0"}))


if __name__ == "__main__":
    unittest.main()
